leasemanagement/Models/Contract.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LeaseManagement.Models
{
    public class Contract : Timestamp
    {
        public Contract()
        {
            ContractDocuments = new List<ContractDocument>();
            Actions = new List<Action>();
        }

        public int Id { get; set; }
        public Organization Organization { get; set; }

        public ICollection<ContractDocument> ContractDocuments { get; set; }

        public ICollection<Action> Actions { get; set; }

        public string Name { get; set; }
        public string Description { get; set; }
        public Status Status { get; set; }

    }
}

leasemanagement/ViewModels/StoreViewModel.cs
using LeaseManagement.Data;
using LeaseManagement.Data.Domain;
using LeaseManagement.Service;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LeaseManagement.ViewModels
{
    public class StoreViewModel 
    {
        public List<Contract> Contracts { get; set; }

    }
}

leasemanagement/Controllers/ContractsController.cs
using LeaseManagement.Data.Domain;
using LeaseManagement.Service;
using LeaseManagement.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LeaseManagement.Controllers
{
    public class ContractsController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ILeaseManagementDataService _dataService;
        public ContractsController(ILogger<HomeController> logger, ILeaseManagementDataService dataService)
        {
            _logger = logger;
            _dataService = dataService;
        }

        [HttpGet("store")]
        public List<Contract> getAllContracts()
        {
            return _dataService.GetAllContracts().ToList();
        }

        public IActionResult Store()
        {
            var model = new StoreViewModel();
            model.Contracts = getAllContracts();

            return View(model);
        }

        public IActionResult UploadFile(IFormFile file)
        {
            if (Request != null)
            {

                //Confirm file was provided
                if ((file != null) && (file.Length > 0) && !string.IsNullOrEmpty(file.FileName))
                {
                    //if (CloudStorageAccount.TryParse(_config["StorageConnection"], out CloudStorageAccount storageAccount))
                    //{
                    //    CloudBlobClient blobClient = storageAccount.CreateCloudBlobClient();

                    //    CloudBlobContainer container = blobClient.GetContainerReference("test");

                    //    bool result = await container.CreateIfNotExistsAsync();


                    //    CloudBlockBlob blockBlob = container.GetBlockBlobReference(file.FileName);

                    //    await blockBlob.UploadFromStreamAsync(file.OpenReadStream());

                    //}
                    //else
                    //{
                    //    throw new Exception("");
                    //}
                }

            }

            return RedirectToAction("Store");
        }

        public void Identify()
        {

        }


    }
}

leasemanagement/Views/Contracts/Identify.cshtml
@{
}

leasemanagement/Views/Contracts/Store.cshtml
@model StoreViewModel

@{
    ViewData["Title"] = "Store";
    int i = 0;
}

<link rel="stylesheet" href="~/css/Store.css" />
@if (Model.Contracts != null)
{
    <div class="page-ribbon d-flex align-items-center">
        <div class="container d-flex">
            <span>Store</span>
        </div>

    </div>

    <div class="container bg-lightgrey">

        <div class="d-flex justify-content-center pb-3">
            <a role="button" class="btn-primary darkBtn" asp-action="Index">UPLOAD</a>
        </div>

        <div class="d-inline-flex bg-white justify-content-around flex-sm-column flex-md-row flex-lg-row flex-fill flex-wrap storeDiv w-100">

            <div id="ContractList" class="d-flex flex-column px20">
                <div class="accordion">
                    <div class="card-wrap">

                        @foreach (var contract in Model.Contracts)
                        {
                            <div class="card d-flex flex-column w-100 accordion-data">
                                <div class="card-header d-flex flex-column w-100 accordion-data contract" id="contract-@i">
                                    <a role="button" class="panel-title @(i == 0 ? "" : "collapsed")" data-toggle="collapse"
                                       data-target="#docs-@i" aria-expanded="@(i == 0 ? "true" : "false")"
                                       aria-controls="#docs-@i">
                                        <span class="contract-name"><b>@contract.Name</b></span>

                                    </a>
                                </div>

                                <div id="docs-@i" class="collapse @(i == 0 ? "show" : "")" aria-labelledby="#contract-@i">
                                    <div class="card-body py-0">
                                        <div class="d-flex flex-sm-column flex-md-row flex-lg-row flex-fill align-items-center flex-wrap contract-text">

                                            @foreach (var doc in contract.ContractDocuments)
                                            {
                                                <div class="d-flex flex-column" id="docHierarchy">
                                                    <div class="accordion w-100">
                                                        @*<div class="card-wrap">*@

                                                        <div class="card-header d-flex flex-column w-100 accordion-data master" id="master-@i">
                                                            <a role="button" class="panel-title @(i == 0 ? "" : "collapsed")" data-toggle="collapse"
                                                               data-target="#rev-@i" aria-expanded="@(i == 0 ? "true" : "false")"
                                                               aria-controls="#master-@i">
                                                                <span class="doc-name"><b>@doc.Name</b></span>

                                                            </a>
                                                        </div>
                                                        <div id="rev-@i" class="collapse @(i == 0 ? "show" : "")" aria-labelledby="#master-@i">
                                                            <div class="card-body">
                                                                @foreach (var rev in doc.ContractScratchDocuments)
                                                                {
                                                                    <div class="d-flex flex-sm-column flex-md-row flex-lg-row flex-fill align-items-center flex-wrap rev-text">
                                                                        @rev.Name
                                                                    </div>
                                                                }
                                                            </div>
                                                        </div>

                                                        @*</div>*@

                                                    </div>

                                                </div>
                                            }

                                        </div>
                                    </div>

                                </div>
                            </div>
                            i = i + 1;
                        }

                    </div>
                </div>
            </div>

            <div id="DocCarousel" class="d-flex justify-content-center align-items-center px20 m10 border-black">

                This is the div where the preview of document images will be seen in a carousel.
                <br />On click, the document will open in a new tab.

            </div>
        </div>

    </div>
}
else
{
    <div class="d-flex align-items-center justify-content-center empty">No contracts uploaded yet.</div>
}

@*@foreach (var contract in Model.Contracts)
    {
        <nav class="nav" role="navigation">
            <ul class="nav__list">
                <li>
                    <input id="group-@contract.Id" type="checkbox" hidden />
                    <label for="group-@contract.Id"><span class="fa fa-angle-right"></span>@contract.Name</label>
                    <ul class="group-list">
                        <li>

                            @foreach (var document in contract.ContractDocuments)
                            {
                                <input id="sub-group-@document.Id" type="checkbox" hidden />
                                <label for="sub-group-@document.Id"><span class="fa fa-angle-right"></span>@document.Name</label>
                                <ul class="sub-group-list">
                                    @foreach (var scratchDocument in document.ContractScratchDocuments)
                                    {
                                        <li><a href="#">@scratchDocument.Name</a></li>
                                    }
                                </ul>
                            }
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
    }*@

leasemanagement/Views/Contracts/Upload.cshtml
@using (Html.BeginForm("UploadFile", "Contracts", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    <!-- SEER APP TITLES GOES HERE -->
    <div>
        <h1>Upload Blob File</h1>
    </div>
    <!-- SEER APP TITLES GOES HERE ENDS -->
    <div>

        <h3><span class="fa fa-file-code-o "></span> Blob file</h3>
        <div class="InputGroup">
            <input type="file" name="file" />
            <input type="submit" name="Submit" value="Submit" />
            <!--test-->
        </div>
    </div>
}